### ISSUE TITLE
run.sh syntax errors

### ISSUE THREAD

**Issue by Nomadjackalope** [smartgic/docker-mycroft#16]
Lines 45 and 46 contain syntax errors where the : should be ;
 They are currently

45: `m) modelsfolder=${OPTARG};:`

46: `s) cachefolder=${OPTARG};:`

but should be

45: `m) modelsfolder=${OPTARG};;`

46: `s) cachefolder=${OPTARG};;`

**Comment by goldyfruit** [comment]
Thanks for reporting the issue.
Fixed.
