### ISSUE TITLE
Precise could not be downloaded(

### ISSUE THREAD

**Issue by vallard** [smartgic/docker-mycroft#3]
Thanks for making this cool project.  In the logs of the stable version `mycroft-voice:stable` I see the logs say: 

```
Precise could not be downloaded(ValueError('Invalid MD5 url: https://github.com/MycroftAI/mycroft-precise/releases/download/v0.2.0/precise-engine_0.2.0_armv7l.tar.gz.md5'))
```

**Comment by goldyfruit** [comment]
Hi @vallard 

> Thanks for making this cool project
You're welcome :+1: 

This error is not related to the Docker images itself, it's more related to Mycroft which is trying to download the `md5sum` file.
I tried to download the file manually and it worked, I compared the checksum between the the `tar.gz` and the the `md5sum` file and they are identical.

A weird thing is that it tries to download an older version of Precise Engine *(0.2.0)* which should be 0.3.0. I poked some guys on Mycroft chat, I'll keep you posted with update.

**Comment by goldyfruit** [comment]
After some discussion, `0.3.0` is the default for `aarch64` architecture.

Does your RPi still have access to Internet? If you try to run this command from your RPi, does it work?
```
$ wget https://github.com/MycroftAI/mycroft-precise/releases/download/v0.2.0/precise-engine_0.2.0_armv7l.tar.gz.md5
```

**Comment by vallard** [comment]
Yes, that works fine from the command line on the RPI.

**Comment by vallard** [comment]
logging into the container I get the following: 

```
$ docker exec -it dfb /bin/bash
$ curl -O https://github.com/MycroftAI/mycroft-precise/releases/download/v0.2.0/precise-engine_0.2.0_armv7l.tar.gz.md5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by goldyfruit** [comment]
Try the `-k` option with `curl`.

**Comment by vallard** [comment]
Yeah that works but still doesn’t solve the issue that the code is trying to download it and not able to.

**Comment by goldyfruit** [comment]
Did you try the `c_rehash` as `root` within the container?

**Comment by vallard** [comment]
Hmmm. I’m not sure what that is.  I haven’t modified the container images at all. Was just trying to make it all run. Maybe there are other problems.  Thanks for your help though.

**Comment by goldyfruit** [comment]
You will have nothing to install, `c_rehash` is part of the `openssl` package already install within the image.
http://manpages.ubuntu.com/manpages/trusty/man1/c_rehash.1ssl.html

**Comment by vallard** [comment]
```
mycroft@mycroft_voice:~/core$ c_rehash
Skipping /usr/lib/ssl/certs, can't write
mycroft@mycroft_voice:~/core$ sudo c_rehash
bash: sudo: command not found
```

Is this the problem?

**Comment by goldyfruit** [comment]
To connect as `root` inside a container, you don't need `sudo`.
```
$ sudo docker exec -ti -u 0 mycroft_voice bash
root@mycroft_voice:/home/mycroft/core# c_rehash
```
Output:
```
Doing /usr/lib/ssl/certs
WARNING: Skipping duplicate certificate ca-certificates.crt
WARNING: Skipping duplicate certificate ca-certificates.crt
```
Then restart the container.

**Comment by vallard** [comment]
I think that may have worked!  Thank you, seeing this now, but wake word is being detected.  Prob something else I have wrong on my end. 
```
2021-02-23 05:33:40.873 | ERROR    |     1 | mycroft.client.speech.hotword_factory:update_precise:240 | Precise could not be downloaded(PermissionError(13, 'Permission denied'))
2021-02-23 05:33:43.998 | INFO     |     1 | mycroft.client.speech.hotword_factory:during_download:301 | Still downloading executable...
2021-02-23 05:33:44.733 | INFO     |     1 | mycroft.client.speech.hotword_factory:during_download:301 | Still downloading executable...
2021-02-23 05:33:45.368 | INFO     |     1 | mycroft.client.speech.hotword_factory:during_download:301 | Still downloading executable...
2021-02-23 05:33:45.872 | INFO     |     1 | mycroft.client.speech.hotword_factory:during_download:301 | Still downloading executable...
2021-02-23 05:34:14.002 | INFO     |     1 | mycroft.client.speech.hotword_factory:during_download:301 | Still downloading executable...
2021-02-23 05:34:14.736 | INFO     |     1 | mycroft.client.speech.hotword_factory:during_download:301 | Still downloading executable...
2021-02-23 05:34:15.381 | INFO     |     1 | mycroft.client.speech.hotword_factory:during_download:301 | Still downloading executable...
2021-02-23 05:34:15.877 | INFO     |     1 | mycroft.client.speech.hotword_factory:during_download:301 | Still downloading executable...
2021-02-23 05:34:41.368 | INFO     |     1 | mycroft.client.speech.hotword_factory:on_download:289 | Downloading Precise executable...
2021-02-23 05:34:41.373 | ERROR    |     1 | mycroft.client.speech.hotword_factory:update_precise:240 | Precise could not be downloaded(PermissionError(13, 'Permission denied'))
```

**Comment by goldyfruit** [comment]
> I think that may have worked! 
Great, I'll add this to the `Dockerfile`.

> 
> ```
> 2021-02-23 05:33:40.873 | ERROR    |     1 | mycroft.client.speech.hotword_factory:update_precise:240 | Precise could not be downloaded(PermissionError(13, 'Permission denied'))
> 2021-02-23 05:33:43.998 | INFO     |     1 | mycroft.client.speech.hotword_factory:during_download:301 | Still downloading executable...
> 2021-02-23 05:33:44.733 | INFO     |     1 | mycroft.client.speech.hotword_factory:during_download:301 | Still downloading executable...
> 2021-02-23 05:33:45.368 | INFO     |     1 | mycroft.client.speech.hotword_factory:during_download:301 | Still downloading executable...
> 2021-02-23 05:33:45.872 | INFO     |     1 | mycroft.client.speech.hotword_factory:during_download:301 | Still downloading executable...
> 2021-02-23 05:34:14.002 | INFO     |     1 | mycroft.client.speech.hotword_factory:during_download:301 | Still downloading executable...
> 2021-02-23 05:34:14.736 | INFO     |     1 | mycroft.client.speech.hotword_factory:during_download:301 | Still downloading executable...
> 2021-02-23 05:34:15.381 | INFO     |     1 | mycroft.client.speech.hotword_factory:during_download:301 | Still downloading executable...
> 2021-02-23 05:34:15.877 | INFO     |     1 | mycroft.client.speech.hotword_factory:during_download:301 | Still downloading executable...
> 2021-02-23 05:34:41.368 | INFO     |     1 | mycroft.client.speech.hotword_factory:on_download:289 | Downloading Precise executable...
> 2021-02-23 05:34:41.373 | ERROR    |     1 | mycroft.client.speech.hotword_factory:update_precise:240 | Precise could not be downloaded(PermissionError(13, 'Permission denied'))
> ```

I think you have created the `mycroft-config` as `root` which means that `mycroft_voice` which is running as `mycroft` user cannot right into it.

Adjust the permissions on this directory to make it writable within the container.

**Comment by goldyfruit** [comment]
I pushed two commits, one for the `c_rehash` command and the other about the `Permission denied`.
https://github.com/smartgic/docker-mycroft/commit/3ee8fd1cb364e14625ae0399dcc68dcb9f624732
https://github.com/smartgic/docker-mycroft/commit/c0099cad44feda2435bd1d54dd9280b42c46b495

**Comment by goldyfruit** [comment]
I just build new images with the fix for the `stable` tag.

**Comment by goldyfruit** [comment]
@vallard does everything is fixed for you?

**Comment by vallard** [comment]
Yes, fixing the directory permissions helped like you said and the system registered.  Thank you so much for your help!

**Comment by goldyfruit** [comment]
> Yes, fixing the directory permissions helped like you said and the system registered. Thank you so much for your help!

Yeah!
Thanks for reporting the issue :+1:
