### ISSUE TITLE
custom device "/dev/gpiomem": no such file or directory

### ISSUE THREAD

**Issue by bryanpedini** [smartgic/docker-mycroft#8]
It seems like `docker-compose.yml` is built more towards Raspberry Pis, but the `/dev/gpiomem` kernel device does not exist in `amd64` Linux computers.

Since there is the ability to specify the Docker-Compose filename, can we create a file like `rpi-compose.yml` and remove the `/dev/gpiomem` device in the original `docker-compose.yml`? Removing (or commenting) [docker-compose.yml#L108](https://github.com/smartgic/docker-mycroft/blob/f05cb579ee224c00a1fe7044908ec21021d17053/docker-compose.yml#L108) seems to make it work just fine on Docker under Ubuntu 20.04 LTS.

Thanks in advance!

**Comment by goldyfruit** [comment]
@bryanpedini thanks for the feedback, indeed the focus has been out on the Raspberry Pi but you are totally right.

**Comment by bryanpedini** [comment]
Do you want me to take a look and possibly create a PR?

**Comment by goldyfruit** [comment]
> Do you want me to take a look and possibly create a PR?

It would be great 😜

**Comment by bryanpedini** [comment]
@goldyfruit sorry for the ping.
I've opened the PR, could you take a look?
Thanks.
